-- TaskManager Database Schema
-- This schema is auto-generated by JPA/Hibernate
-- Run this manually if needed, or let JPA create it automatically

-- Create database (MySQL)
CREATE DATABASE IF NOT EXISTS taskdb;
USE taskdb;

-- Users table
CREATE TABLE IF NOT EXISTS users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

-- User roles table
CREATE TABLE IF NOT EXISTS user_roles (
    user_id BIGINT NOT NULL,
    role VARCHAR(20) NOT NULL,
    PRIMARY KEY (user_id, role),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Tasks table
CREATE TABLE IF NOT EXISTS tasks (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    user_id BIGINT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Indexes for better performance
CREATE INDEX idx_username ON users(username);
CREATE INDEX idx_user_id ON tasks(user_id);
CREATE INDEX idx_created_at ON tasks(created_at);

-- Sample data (optional - DataSeeder will create these)
-- Admin user: admin / admin123 (hashed)
-- Regular user: user / user123 (hashed)


